# Generated by Django 4.2.2 on 2023-08-09 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baladiya', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='commune',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='baladiya.commune'),
        ),
    ]
