# Generated by Django 4.2.2 on 2023-07-28 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baladiya', '0005_alter_activity_created_at_alter_activity_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accompagnement',
            name='state',
            field=models.CharField(choices=[('en traitement', 'en traitement'), ('validé', 'validé'), ('refusé', 'refusé')], default='en traitement', max_length=20),
        ),
        migrations.AddField(
            model_name='accompagnement',
            name='type',
            field=models.CharField(blank=True, choices=[('Economique', 'Economique')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='state',
            field=models.CharField(choices=[('en traitement', 'en traitement'), ('validé', 'validé'), ('refusé', 'refusé')], default='en traitement', max_length=20),
        ),
        migrations.AddField(
            model_name='formation',
            name='state',
            field=models.CharField(choices=[('en traitement', 'en traitement'), ('validé', 'validé'), ('refusé', 'refusé')], default='en traitement', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='topics_images'),
        ),
        migrations.AddField(
            model_name='topic',
            name='state',
            field=models.CharField(choices=[('en traitement', 'en traitement'), ('validé', 'validé'), ('refusé', 'refusé')], default='en traitement', max_length=20),
        ),
        migrations.AddField(
            model_name='topic',
            name='type',
            field=models.CharField(blank=True, choices=[('Sportif', 'Sportif'), ('Politique', 'Politique'), ('Social', 'Social'), ('Patronat local', 'Patronat local'), ('Culturel', 'Culturel'), ('Audiance', 'Audiance')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='accompagnement',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accompagnements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activity',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='formation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products_images')),
                ('action_type', models.CharField(choices=[('Vente', 'Vente'), ('Echange', 'Echange'), ('Allocation', 'Allocation')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EcologicalInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('en traitement', 'en traitement'), ('validé', 'validé'), ('refusé', 'refusé')], default='en traitement', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='ecological_infos_images')),
                ('type', models.CharField(choices=[('sensibilisation', 'sensibilisation'), ('valorisation', 'valorisation')], max_length=15)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecological_informations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
