# Generated by Django 4.2.2 on 2023-08-04 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baladiya', '0006_accompagnement_state_accompagnement_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='wilaya',
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(blank=True, choices=[('Politique', 'Politique'), ('Economique', 'Economique')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='user_img'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='type',
            field=models.CharField(blank=True, choices=[('Sportif', 'Sportif'), ('Politique', 'Politique'), ('Social', 'Social'), ('Patronat local', 'Patronat local'), ('Culturel', 'Culturel'), ('Audiance', 'Audiance'), ('Economique', 'Economique')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Citoyen', 'Citoyen'), ('Admin', 'Admin'), ('Agent', 'Agent'), ('Association', 'Association'), ('Entrepreneur', 'Entreprneur')], default='Citoyen', max_length=15),
        ),
        migrations.CreateModel(
            name='AudianceDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('state', models.CharField(choices=[('en traitement', 'en traitement'), ('validé', 'validé'), ('refusé', 'refusé')], default='en traitement', max_length=20)),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audiance_demands', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
